### ISSUE TITLE
サービスの名前

### ISSUE THREAD

**Issue by sniper-fly** [42supporters-hackason/P2P-matching#123]
いい感じの名前

**Comment by sniper-fly** [comment]
P2P-matching
始祖にしてずっと使ってきた名前。
リポジトリ名もこれ。

**Comment by sniper-fly** [comment]
> P2P-matching 始祖にしてずっと使ってきた名前。 リポジトリ名もこれ。
pros
メンバーには馴染みがある
cons
この名前からペアプロする感じのイメージが湧かない

**Comment by sniper-fly** [comment]
ぺあぷろ！

pros
ひらがな４文字ってなんか優しい雰囲気があって良い。「けいおん！」「このすば！」みたいな
「りあクト！」とかもあるし。
あと何をするサービスなのか名前ひと目でわかる

cons
シックな雰囲気のページには合うのかどうかわからない。
ゆるーい、陽気な、明るい感じのページならこのタイトルも合うと思う

**Comment by sasakiyudai** [comment]
> ぺあぷろ！
これ最高卍

**Comment by taisei-13046** [comment]
> ぺあぷろ！

ありかも👀
