### ISSUE TITLE
コミュニティ分け

### ISSUE THREAD

**Issue by taisei-13046** [42supporters-hackason/P2P-matching#72]

**Comment by taisei-13046** [comment]
- 権限なし
- コミュニティ作成
  - コミュニティ名

**Comment by tacomeet** [comment]
## 要件定義（？）

### ユーザーフロー

ログイン
- 今まで通りGithubでログインする
- 自分が所属するコミュニティ一覧を表示. 
- 「所属するコミュニティ」のどれかをクリックして、今のトップページ的なところへ遷移

communty 一覧からできて欲しいこと
- 「所属するcommunityの表示・遷移」
- 「communityを追加」
  - `community_id` を入力するフォーム
- 「新規community作成」
- 「community へユーザー招待」
  - `invite_id` をコピーできる
- 「community 設定変更」
  - `name` と `img_url` を変更

### 細かい仕様
- （とりあえず） `community` の `owner` 的な存在は作らない
- （とりあえず） `community` への招待は ID を共有することで実現
- マッチングポイントはコミュニティ毎に持つ。（MPの総数がずれるとだるい）


### 用語
- `community`: イメージはslackのworkspace. 例えば、 42tokyo とか

### バックエンド変更点
- `community`の作成（ `id` (uuid), `name`, `img_url`, `invite_id`  ）
  - URLとかには、 `id` を使って、 招待には `invite_id` を使う（?)
- `user_community_info` の作成 ( `id` (autoinc), `user_id`, `community_id`, `matching_point` )
- userに `has_many` 的なやつで `community_info` 持たせる
- API追加
  - `communities(user_id: string)`
  - `create_community(name: string!, img_url: string)`
  - 

### フロントエンド変更点
- communityの一覧ページ
- headerとかにcommunityの一覧ページへのURL
- community作成ページ

### あったら良いな機能

- ポストを投稿する際にどのcommunityにポストするか複数選択可能
- communityを跨いだTL
